### ISSUE TITLE
KeyError with configurator

### ISSUE THREAD

**Issue by nvasion** [Juniper/vSRX-AWS#1]
When trying to run the transit-vpc-pujsh-juniper-config.py I get a key error described below:

`{
  "stackTrace": [
    [
      "/var/task/transit-vpc-push-juniper-config.py",
      531,
      "lambda_handler",
      "record=event['Records'][0]"
    ]
  ],
  "errorType": "KeyError",
  "errorMessage": "'Records'"
}`

What might be the cause of this or how does one fix this issue?

**Comment by akbhat** [comment]
Please reopen if issue not resolved.

**Comment by faheemwadeecx** [comment]
@nvasion  Did you manage to sort out this issue because i'm having the same issue in a different project
