### ISSUE TITLE
Not able to connect this Transit VPC to Transit Gateway as VPC attachment. 

### ISSUE THREAD

**Issue by hardikpanchal006** [Juniper/vSRX-AWS#13]
Not able to connect this Transit VPC to Transit Gateway as VPC attachment. 

We need to inspect traffic between VPC-1 and VPC-2 and the topology is as below

VPC-1 > Transit Gateway > Transit VPC(vSRX) > Transit Gateway > VPC-2

Need urgent help

**Comment by akbhat** [comment]
This TVPC repo is not intended to be used with a Transit GW. That said, can you provide some additional detail about the status of the TVPC vpc attachment to TGW as seen in the console? If the attachment was not made via console, share the CF/TF template used? Confirm that there is no other attachment between TVPC and TGW such as a VPN attachment.

**Comment by hardikpanchal006** [comment]
Abhishek - True. But what we want is basically VPC-1 and VPC-2 connected to Transit Gateway but Traffic should pass via Transit VPC i.e. 2 vSRX in different AZ. How can that be done ? I am not getting any success.  Tried AWS support but such implementation is very new to them.

need help

**Comment by hardikpanchal006** [comment]
![image](https://user-images.githubusercontent.com/52037682/59923730-b9160280-9451-11e9-8828-fd26b4012b10.png)
![image](https://user-images.githubusercontent.com/52037682/59923752-c8954b80-9451-11e9-9192-d868047a79d6.png)

As per the second image, I am not able to attach the Management Subnets. Plus vSRX is not passing any traffic between VPC-1 and VPC-2

**Comment by akbhat** [comment]
The solution you mentioned is not as straightforward. For instance, when TVPC is attached to the TGW, the traffic only reaches the VPC and not the vSRX. Appropriate VPC routing needs to be setup or IPSec VPN can be created between the TGW and the vSRX directly. You can look at the following repo to get an idea of what is needed. https://github.com/akbhat/tgw-transit-vpc
