### ISSUE TITLE
Lambda configurator fails - VPN Tunnels Down

### ISSUE THREAD

**Issue by medarz** [Juniper/vSRX-AWS#5]
Using the template in us-east-1 region, shows that the Clouformation creation succeeds. When Tagging the VGW, VPN tunnels are created, but the Lambda configurator fails. It doesn't configure neither of the vSRX and both tunnels are show as down.

Looking into the Lamba logs, I can see that in one router, the configurator connects successfully. It even generates the AWS_config.txt file. However, no configuration changes are done to the router. 

One minor error I see in the logs is :  

`edit edit: Command not found. root@tvpc-vsrx2% `

Additionally, if I try to load manually the AWS_config.txt file, it shows the following errors:

```
root@tvpc-vsrx2# load override /var/log/AWS_config.txt
load complete

[edit]
root@tvpc-vsrx2# commit check
[edit security ipsec vpn vpn-0ab6de246ef00ffff-1]
  'ike'
    Missing mandatory statement: 'ipsec-policy'
[edit security ipsec vpn vpn-0ab6de246ef00ffff-2]
  'ike'
    Missing mandatory statement: 'ipsec-policy'
error: configuration check-out failed: (missing mandatory statements)

[edit]
```

**Comment by medarz** [comment]
Found the issue of why configuration is not currently being provisioned in the Juniper instances. 

The VPN-ID has more characters, which exceeded the 32 permited characters by Juniper.

I see that there is already a pull request with this modification. Hope it can be approved soon, since this solution won't work without that modification

**Comment by akbhat** [comment]
This has already been fixed. Please reopen if you run into this again
